export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const ADDTRIP_START = "ADDTRIP_START";
export const ADDTRIP_SUCCESS = "ADDTRIP_SUCCESS";
export const ADDTRIP_FAILURE = "ADDTRIP_FAILURE";

export const GET_PARENT_START = "GET_PARENT_START";
export const GET_PARENT_SUCCESS = "GET_PARENT_SUCCESS";
export const GET_PARENT_FAILURE = "GET_PARENT_FAILURE";

export const UPDATE_PARENT_START = "UPDATE_PARENT_START";
export const UPDATE_PARENT_SUCCESS = "UPDATE_PARENT_SUCCESS";
export const UPDATE_PARENT_FAILURE = "UPDATE_PARENT_FAILURE";

export const DELETE_TRIP_START = "DELETE_TRIP_START";
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_FAILURE = "DELETE_TRIP_FAILURE";
